#!/usr/bin/env bash
# Generated by tsh. Requires Bash 3.2 or newer.
__tsh_backend_tmp_1="$(uname -s 2>/dev/null || true)"
__tsh_backend_tmp_0='unknown'
case "${__tsh_backend_tmp_1}" in
  Linux*) __tsh_backend_tmp_0='linux' ;;
  Darwin*) __tsh_backend_tmp_0='macos' ;;
  FreeBSD*) __tsh_backend_tmp_0='freebsd' ;;
  OpenBSD*) __tsh_backend_tmp_0='openbsd' ;;
  NetBSD*) __tsh_backend_tmp_0='netbsd' ;;
  SunOS*) __tsh_backend_tmp_0='solaris' ;;
  CYGWIN*|MINGW*|MSYS*) __tsh_backend_tmp_0='windows' ;;
esac
__tsh_v_platform_0="${__tsh_backend_tmp_0}"
__tsh_backend_tmp_2="$(uname -m 2>/dev/null || true)"
case "${__tsh_backend_tmp_2}" in
  x86_64|amd64|AMD64) __tsh_backend_tmp_2='x86_64' ;;
  aarch64|arm64|ARM64) __tsh_backend_tmp_2='aarch64' ;;
  i386|i486|i586|i686|x86) __tsh_backend_tmp_2='x86' ;;
  armv*|ARMV*) __tsh_backend_tmp_2='arm' ;;
esac
__tsh_v_architecture_1="${__tsh_backend_tmp_2}"
__tsh_backend_tmp_3="${HOME-}"
__tsh_v_home_2="${__tsh_backend_tmp_3}"
__tsh_v_asset_3=''
__tsh_backend_tmp_4="${__tsh_v_platform_0}"
if [[ "${__tsh_backend_tmp_4}" == 'linux' ]]; then
  __tsh_backend_tmp_5=1
else
  __tsh_backend_tmp_5=0
fi
if (( __tsh_backend_tmp_5 != 0 )); then
  __tsh_backend_tmp_6="${__tsh_v_architecture_1}"
  if [[ "${__tsh_backend_tmp_6}" == 'x86_64' ]]; then
    __tsh_backend_tmp_7=1
  else
    __tsh_backend_tmp_7=0
  fi
  if (( __tsh_backend_tmp_7 != 0 )); then
    __tsh_v_asset_3='typedshell-linux-x86_64'
  else
    __tsh_backend_tmp_8="${__tsh_v_architecture_1}"
    if [[ "${__tsh_backend_tmp_8}" == 'aarch64' ]]; then
      __tsh_backend_tmp_9=1
    else
      __tsh_backend_tmp_9=0
    fi
    if (( __tsh_backend_tmp_9 != 0 )); then
      __tsh_v_asset_3='typedshell-linux-aarch64'
    fi
  fi
else
  __tsh_backend_tmp_10="${__tsh_v_platform_0}"
  if [[ "${__tsh_backend_tmp_10}" == 'macos' ]]; then
    __tsh_backend_tmp_11=1
  else
    __tsh_backend_tmp_11=0
  fi
  if (( __tsh_backend_tmp_11 != 0 )); then
    __tsh_backend_tmp_12="${__tsh_v_architecture_1}"
    if [[ "${__tsh_backend_tmp_12}" == 'x86_64' ]]; then
      __tsh_backend_tmp_13=1
    else
      __tsh_backend_tmp_13=0
    fi
    if (( __tsh_backend_tmp_13 != 0 )); then
      __tsh_v_asset_3='typedshell-macos-x86_64'
    else
      __tsh_backend_tmp_14="${__tsh_v_architecture_1}"
      if [[ "${__tsh_backend_tmp_14}" == 'aarch64' ]]; then
        __tsh_backend_tmp_15=1
      else
        __tsh_backend_tmp_15=0
      fi
      if (( __tsh_backend_tmp_15 != 0 )); then
        __tsh_v_asset_3='typedshell-macos-aarch64'
      fi
    fi
  fi
fi
__tsh_backend_tmp_16="${__tsh_v_asset_3}"
if [[ "${__tsh_backend_tmp_16}" == '' ]]; then
  __tsh_backend_tmp_17=1
else
  __tsh_backend_tmp_17=0
fi
if (( __tsh_backend_tmp_17 != 0 )); then
  __tsh_backend_tmp_18=''
  __tsh_backend_tmp_18="${__tsh_backend_tmp_18}"'Unsupported TypedShell install target: '
  __tsh_backend_tmp_18="${__tsh_backend_tmp_18}""${__tsh_v_platform_0}"
  __tsh_backend_tmp_18="${__tsh_backend_tmp_18}"'/'
  __tsh_backend_tmp_18="${__tsh_backend_tmp_18}""${__tsh_v_architecture_1}"
  printf '%s\n' "${__tsh_backend_tmp_18}" || exit $?
  __tsh_backend_tmp_19=1
  exit "${__tsh_backend_tmp_19}"
fi
__tsh_backend_tmp_20=''
__tsh_backend_tmp_20="${__tsh_backend_tmp_20}""${__tsh_v_home_2}"
__tsh_backend_tmp_20="${__tsh_backend_tmp_20}"'/.typedshell'
__tsh_v_installDir_4="${__tsh_backend_tmp_20}"
__tsh_backend_tmp_21=''
__tsh_backend_tmp_21="${__tsh_backend_tmp_21}""${__tsh_v_installDir_4}"
__tsh_backend_tmp_21="${__tsh_backend_tmp_21}"'/tsh'
__tsh_v_executable_5="${__tsh_backend_tmp_21}"
__tsh_backend_tmp_22="${__tsh_v_platform_0}"
if [[ "${__tsh_backend_tmp_22}" == 'windows' ]]; then
  __tsh_backend_tmp_23=1
else
  __tsh_backend_tmp_23=0
fi
if (( __tsh_backend_tmp_23 != 0 )); then
  __tsh_backend_tmp_24=''
  __tsh_backend_tmp_24="${__tsh_backend_tmp_24}""${__tsh_v_executable_5}"
  __tsh_backend_tmp_24="${__tsh_backend_tmp_24}"'.exe'
  __tsh_v_executable_5="${__tsh_backend_tmp_24}"
fi
__tsh_backend_tmp_25=''
__tsh_backend_tmp_25="${__tsh_backend_tmp_25}""${__tsh_v_installDir_4}"
__tsh_backend_tmp_25="${__tsh_backend_tmp_25}"'/tsh-download.tmp'
__tsh_v_downloadPath_6="${__tsh_backend_tmp_25}"
__tsh_backend_tmp_26=''
__tsh_backend_tmp_26="${__tsh_backend_tmp_26}"'https://github.com/twlite/typedshell/releases/latest/download/'
__tsh_backend_tmp_26="${__tsh_backend_tmp_26}""${__tsh_v_asset_3}"
__tsh_v_downloadUrl_7="${__tsh_backend_tmp_26}"
__tsh_backend_tmp_27="${__tsh_v_installDir_4}"
mkdir -p -- "${__tsh_backend_tmp_27}" || exit $?
__tsh_backend_tmp_28="${__tsh_v_downloadPath_6}"
__tsh_backend_tmp_29="${__tsh_v_downloadUrl_7}"
'curl' '-fLsS' '--retry' '3' '-o' "${__tsh_backend_tmp_28}" "${__tsh_backend_tmp_29}" || exit $?
__tsh_backend_tmp_30="${__tsh_v_downloadPath_6}"
__tsh_backend_tmp_31="${__tsh_v_executable_5}"
mv -- "${__tsh_backend_tmp_30}" "${__tsh_backend_tmp_31}" || exit $?
__tsh_backend_tmp_32="${__tsh_v_executable_5}"
__tsh_backend_tmp_33='755'
chmod -- "${__tsh_backend_tmp_33}" "${__tsh_backend_tmp_32}" || exit $?
__tsh_backend_tmp_34="${__tsh_v_installDir_4}"
__tsh_backend_tmp_35="${__tsh_backend_tmp_34}"
if [[ "${__tsh_backend_tmp_35}" != /* ]]; then __tsh_backend_tmp_35="$PWD/${__tsh_backend_tmp_35}"; fi
while [[ "${__tsh_backend_tmp_35}" != / && "${__tsh_backend_tmp_35}" == */ ]]; do __tsh_backend_tmp_35="${__tsh_backend_tmp_35%/}"; done
if [[ -z "${__tsh_backend_tmp_35}" || "${__tsh_backend_tmp_35}" == *:* ]]; then
  exit 1
fi
case ":${PATH-}:" in *:"${__tsh_backend_tmp_35}":*) ;; *) if [[ -n "${PATH-}" ]]; then export PATH="${__tsh_backend_tmp_35}:${PATH}"; else export PATH="${__tsh_backend_tmp_35}"; fi ;; esac
__tsh_backend_tmp_36=${__tsh_backend_tmp_35//\\/\\\\}
__tsh_backend_tmp_36=${__tsh_backend_tmp_36//\"/\\\"}
__tsh_backend_tmp_36=${__tsh_backend_tmp_36//\$/\\\$}
__tsh_backend_tmp_36=${__tsh_backend_tmp_36//\`/\\\`}
printf -v __tsh_backend_tmp_37 'case ":$PATH:" in *:"%s:"*) ;; *) if [ -n "$PATH" ]; then export PATH="%s:$PATH"; else export PATH="%s"; fi ;; esac' "${__tsh_backend_tmp_36}" "${__tsh_backend_tmp_36}" "${__tsh_backend_tmp_36}"
__tsh_add_profile_line() {
  local profile_path="$1" path_line="$2"
  if ! grep -Fqx "$path_line" "$profile_path" 2>/dev/null; then
    mkdir -p -- "$(dirname "$profile_path")" || exit $?
    printf '\n%s\n' "$path_line" >> "$profile_path" || exit $?
  fi
}
case "${SHELL-}" in
  */zsh) __tsh_add_profile_line "$HOME/.zshrc" "${__tsh_backend_tmp_37}"; __tsh_add_profile_line "$HOME/.zprofile" "${__tsh_backend_tmp_37}" ;;
  */bash)
    __tsh_add_profile_line "$HOME/.bashrc" "${__tsh_backend_tmp_37}"
    if [ -f "$HOME/.bash_profile" ]; then
      __tsh_add_profile_line "$HOME/.bash_profile" "${__tsh_backend_tmp_37}"
    elif [ -f "$HOME/.bash_login" ]; then
      __tsh_add_profile_line "$HOME/.bash_login" "${__tsh_backend_tmp_37}"
    else
      __tsh_add_profile_line "$HOME/.profile" "${__tsh_backend_tmp_37}"
    fi
  ;;
  */fish)
    __tsh_backend_tmp_38=${__tsh_backend_tmp_35}
    __tsh_backend_tmp_38=${__tsh_backend_tmp_38//\\/\\\\}
    __tsh_backend_tmp_38=${__tsh_backend_tmp_38//\'/\\\'}
    printf -v __tsh_backend_tmp_39 "fish_add_path '%s'" "${__tsh_backend_tmp_38}"
    __tsh_add_profile_line "$HOME/.config/fish/conf.d/typedshell.fish" "${__tsh_backend_tmp_39}"
  ;;
  *)
    __tsh_add_profile_line "$HOME/.profile" "${__tsh_backend_tmp_37}"
  ;;
esac
__tsh_backend_tmp_40=''
__tsh_backend_tmp_40="${__tsh_backend_tmp_40}"'Installed tsh to '
__tsh_backend_tmp_40="${__tsh_backend_tmp_40}""${__tsh_v_executable_5}"
__tsh_backend_tmp_40="${__tsh_backend_tmp_40}"'. Open a new terminal to use it from PATH.'
printf '%s\n' "${__tsh_backend_tmp_40}" || exit $?
