# Generated by tsh. Requires PowerShell 7.4 or newer.
$ErrorActionPreference = 'Continue'
$__tsh_tmp_0 = 'unknown'
if ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)) { $__tsh_tmp_0 = 'windows' }
elseif ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Linux)) { $__tsh_tmp_0 = 'linux' }
elseif ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::OSX)) { $__tsh_tmp_0 = 'macos' }
elseif ([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Create('FREEBSD'))) { $__tsh_tmp_0 = 'freebsd' }
$__tsh_v_platform_0 = $__tsh_tmp_0
$__tsh_tmp_2 = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
switch ($__tsh_tmp_2) {
    'X64' { $__tsh_tmp_1 = 'x86_64' }
    'Arm64' { $__tsh_tmp_1 = 'aarch64' }
    'X86' { $__tsh_tmp_1 = 'x86' }
    'Arm' { $__tsh_tmp_1 = 'arm' }
    default { $__tsh_tmp_1 = $__tsh_tmp_2.ToLowerInvariant() }
}
$__tsh_v_architecture_1 = $__tsh_tmp_1
$__tsh_tmp_3 = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile)
if (-not $__tsh_tmp_3) { $__tsh_tmp_3 = $HOME }
$__tsh_v_home_2 = $__tsh_tmp_3
$__tsh_v_asset_3 = ''
$__tsh_tmp_4 = $__tsh_v_platform_0
if (($__tsh_tmp_4 -ceq 'linux')) {
    $__tsh_tmp_5 = $__tsh_v_architecture_1
    if (($__tsh_tmp_5 -ceq 'x86_64')) {
        $__tsh_v_asset_3 = 'typedshell-linux-x86_64'
    } else {
        $__tsh_tmp_6 = $__tsh_v_architecture_1
        if (($__tsh_tmp_6 -ceq 'aarch64')) {
            $__tsh_v_asset_3 = 'typedshell-linux-aarch64'
        }
    }
} else {
    $__tsh_tmp_7 = $__tsh_v_platform_0
    if (($__tsh_tmp_7 -ceq 'macos')) {
        $__tsh_tmp_8 = $__tsh_v_architecture_1
        if (($__tsh_tmp_8 -ceq 'x86_64')) {
            $__tsh_v_asset_3 = 'typedshell-macos-x86_64'
        } else {
            $__tsh_tmp_9 = $__tsh_v_architecture_1
            if (($__tsh_tmp_9 -ceq 'aarch64')) {
                $__tsh_v_asset_3 = 'typedshell-macos-aarch64'
            }
        }
    }
}
$__tsh_tmp_10 = $__tsh_v_platform_0
$__tsh_tmp_11 = $false
if (($__tsh_tmp_10 -ceq 'windows')) {
    $__tsh_tmp_12 = $__tsh_v_architecture_1
    $__tsh_tmp_11 = ($__tsh_tmp_12 -ceq 'x86_64')
}
if ($__tsh_tmp_11) {
    $__tsh_v_asset_3 = 'typedshell-windows-x86_64.exe'
}
$__tsh_tmp_13 = $__tsh_v_asset_3
if (($__tsh_tmp_13 -ceq '')) {
    $__tsh_tmp_14 = ''
    $__tsh_tmp_14 = ($__tsh_tmp_14 + 'Unsupported TypedShell install target: ')
    $__tsh_tmp_14 = ($__tsh_tmp_14 + $__tsh_v_platform_0)
    $__tsh_tmp_14 = ($__tsh_tmp_14 + '/')
    $__tsh_tmp_14 = ($__tsh_tmp_14 + $__tsh_v_architecture_1)
    $__tsh_tmp_15 = ''
    $__tsh_tmp_15 = ($__tsh_tmp_15 + $__tsh_tmp_14)
    [Console]::WriteLine($__tsh_tmp_15)
    $__tsh_tmp_16 = 1
    exit $__tsh_tmp_16
}
$__tsh_tmp_17 = ''
$__tsh_tmp_17 = ($__tsh_tmp_17 + $__tsh_v_home_2)
$__tsh_tmp_17 = ($__tsh_tmp_17 + '/.typedshell')
$__tsh_v_installDir_4 = $__tsh_tmp_17
$__tsh_tmp_18 = ''
$__tsh_tmp_18 = ($__tsh_tmp_18 + $__tsh_v_installDir_4)
$__tsh_tmp_18 = ($__tsh_tmp_18 + '/tsh')
$__tsh_v_executable_5 = $__tsh_tmp_18
$__tsh_tmp_19 = $__tsh_v_platform_0
if (($__tsh_tmp_19 -ceq 'windows')) {
    $__tsh_tmp_20 = ''
    $__tsh_tmp_20 = ($__tsh_tmp_20 + $__tsh_v_executable_5)
    $__tsh_tmp_20 = ($__tsh_tmp_20 + '.exe')
    $__tsh_v_executable_5 = $__tsh_tmp_20
}
$__tsh_tmp_21 = ''
$__tsh_tmp_21 = ($__tsh_tmp_21 + $__tsh_v_installDir_4)
$__tsh_tmp_21 = ($__tsh_tmp_21 + '/tsh-download.tmp')
$__tsh_v_downloadPath_6 = $__tsh_tmp_21
$__tsh_tmp_22 = ''
$__tsh_tmp_22 = ($__tsh_tmp_22 + 'https://github.com/twlite/typedshell/releases/latest/download/')
$__tsh_tmp_22 = ($__tsh_tmp_22 + $__tsh_v_asset_3)
$__tsh_v_downloadUrl_7 = $__tsh_tmp_22
$__tsh_tmp_23 = $__tsh_v_installDir_4
$null = New-Item -ItemType Directory -Path $__tsh_tmp_23 -Force
if (-not $?) { exit 1 }
$__tsh_tmp_24 = $__tsh_v_downloadPath_6
$__tsh_tmp_25 = $__tsh_v_downloadUrl_7
$__tsh_tmp_26 = New-Object System.Diagnostics.ProcessStartInfo
$__tsh_tmp_26.FileName = 'curl.exe'
$__tsh_tmp_26.UseShellExecute = $false
foreach ($__tsh_tmp_28 in @('-fLsS', '--retry', '3', '-o', $__tsh_tmp_24, $__tsh_tmp_25)) { $__tsh_tmp_26.ArgumentList.Add($__tsh_tmp_28) }
try {
    $__tsh_tmp_27 = [System.Diagnostics.Process]::Start($__tsh_tmp_26)
} catch {
    exit 1
}
$__tsh_tmp_27.WaitForExit()
if ($__tsh_tmp_27.ExitCode -ne 0) { exit $__tsh_tmp_27.ExitCode }
$__tsh_tmp_29 = $__tsh_v_downloadPath_6
$__tsh_tmp_30 = $__tsh_v_executable_5
Move-Item -LiteralPath $__tsh_tmp_29 -Destination $__tsh_tmp_30 -Force -Confirm:$false
if (-not $?) { exit 1 }
$__tsh_tmp_31 = $__tsh_v_installDir_4
$__tsh_path = [System.IO.Path]::GetFullPath([string]($__tsh_tmp_31))
if ([string]::IsNullOrEmpty($__tsh_path) -or $__tsh_path.Contains([string][System.IO.Path]::PathSeparator)) { throw 'TypedShell.addPath expects a non-empty path without a PATH separator.' }
$__tsh_separator = [string][System.IO.Path]::PathSeparator
$__tsh_comparison = [System.StringComparison]::Ordinal
if ($IsWindows) { $__tsh_comparison = [System.StringComparison]::OrdinalIgnoreCase }
$__tsh_normalized = $__tsh_path.TrimEnd([char[]]@('\', '/'))
if (-not $__tsh_normalized) { $__tsh_normalized = $__tsh_path }
$__tsh_process_entries = @($env:PATH -split [regex]::Escape($__tsh_separator) | Where-Object { $_ })
$__tsh_process_has_path = $false
foreach ($__tsh_entry in $__tsh_process_entries) {
    if ($__tsh_entry.TrimEnd([char[]]@('\', '/')).Equals($__tsh_normalized, $__tsh_comparison)) { $__tsh_process_has_path = $true; break }
}
if (-not $__tsh_process_has_path) {
    if ($env:PATH) { $env:PATH = "$__tsh_path$__tsh_separator$env:PATH" } else { $env:PATH = $__tsh_path }
}
if ($IsWindows) {
    $__tsh_user_path = [System.Environment]::GetEnvironmentVariable('Path', 'User')
    $__tsh_user_entries = @($__tsh_user_path -split ';' | Where-Object { $_ })
    $__tsh_user_has_path = $false
    foreach ($__tsh_entry in $__tsh_user_entries) {
        if ($__tsh_entry.TrimEnd([char[]]@('\', '/')).Equals($__tsh_normalized, [System.StringComparison]::OrdinalIgnoreCase)) { $__tsh_user_has_path = $true; break }
    }
    if (-not $__tsh_user_has_path) {
        [System.Environment]::SetEnvironmentVariable('Path', (@($__tsh_user_entries) + $__tsh_path) -join ';', 'User')
        try {
            if (-not ('TypedShellInstallEnvironment' -as [type])) {
                Add-Type -TypeDefinition @'
                using System;
                using System.Runtime.InteropServices;
                public static class TypedShellInstallEnvironment {
                    [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
                    public static extern IntPtr SendMessageTimeout(
                        IntPtr hWnd, int message, IntPtr wParam, string lParam,
                        int flags, int timeout, out IntPtr result);
                }
'@
            }
            $__tsh_broadcast_result = [IntPtr]::Zero
            [TypedShellInstallEnvironment]::SendMessageTimeout([IntPtr]::new(-1), 0x001A, [IntPtr]::Zero, 'Environment', 0x0002, 5000, [ref]$__tsh_broadcast_result) | Out-Null
        } catch { Write-Warning 'The user PATH was saved. Open a new terminal to reload it.' }
    }
} else {
    $__tsh_profile_path = $PROFILE.CurrentUserAllHosts
    $__tsh_profile_dir = [System.IO.Path]::GetDirectoryName($__tsh_profile_path)
    $null = [System.IO.Directory]::CreateDirectory($__tsh_profile_dir)
    $__tsh_path_literal = "'" + $__tsh_normalized.Replace("'", "''") + "'"
    $__tsh_profile_line = '$candidate = ' + $__tsh_path_literal + '; $entries = @($env:PATH -split [regex]::Escape([string][System.IO.Path]::PathSeparator)); if ($entries -cnotcontains $candidate) { $env:PATH = if ($env:PATH) { $candidate + [System.IO.Path]::PathSeparator + $env:PATH } else { $candidate } }'
    $__tsh_profile_text = if (Test-Path -LiteralPath $__tsh_profile_path) { [System.IO.File]::ReadAllText($__tsh_profile_path) } else { '' }
    if (-not $__tsh_profile_text.Contains($__tsh_profile_line)) { [System.IO.File]::AppendAllText($__tsh_profile_path, [System.Environment]::NewLine + $__tsh_profile_line + [System.Environment]::NewLine) }
}
$__tsh_tmp_32 = ''
$__tsh_tmp_32 = ($__tsh_tmp_32 + 'Installed tsh to ')
$__tsh_tmp_32 = ($__tsh_tmp_32 + $__tsh_v_executable_5)
$__tsh_tmp_32 = ($__tsh_tmp_32 + '. Open a new terminal to use it from PATH.')
$__tsh_tmp_33 = ''
$__tsh_tmp_33 = ($__tsh_tmp_33 + $__tsh_tmp_32)
[Console]::WriteLine($__tsh_tmp_33)
